### ISSUE TITLE
How to run custom dataset

### ISSUE THREAD

**Issue by atti0127** [lovelyqian/CDFSOD-benchmark#32]
I splitted dataset into train and test set and also made json file for each of them.

I tried running main_result.sh on custom dataset but error occured below.

----------------------------------------------------------------------------------------------------------------------------------
AssertionError: Config file 'configs/aisoc/vitl_shot1_aisoc_finetune.yaml' does not exist!
----------------------------------------------------------------------------------------------------------------------------------

So I copied another yaml files and copied it with modifying dataset names. The problem is that I don't have prototype of my own custom dataset.

CLASS_PROTOTYPES: prototypes_init/aisoc_1shot.vitb14.bbox.p1.sk.pkl

FileNotFoundError: [Errno 2] No such file or directory: 'prototypes_init/aisoc_10shot.vitl14.bbox.pkl'

It seems there are many pkl files in prototypes_init folder with same datasets and same shot. (ex. clipart1k_1shot has 8 different pkl files) 

How do I make all those files with my custom dataset?

**Comment by AImind** [comment]
Please refer to [DATASETS.md](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/DATASETS.md) for detailed instructions.  If you encounter any issues, feel free to reach out to me again.

**Comment by atti0127** [comment]
> Please refer to [DATASETS.md](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/DATASETS.md) for detailed instructions. If you encounter any issues, feel free to reach out to me again.

1. Convert Datasets to COCO Format

2. Split the Dataset into Training and Testing Sets

3. Select k-shot Samples from the Training Set

![image](https://github.com/user-attachments/assets/26cd2354-591b-4dc4-a887-471eed9b44f7)


4. Adding Custom Datasets

![image](https://github.com/user-attachments/assets/f5b675cf-0397-45b8-a9fe-2af952af89ee)

I added my custom datasets_name in builtin.py

![image](https://github.com/user-attachments/assets/39e64e80-e8d9-4b6e-a7ea-5e1b4ea045f6)

Also added datasets_name and CLASS_NAME in categories.py


----------------------------------------------------------------------------------------------------------------------------

I've done all the process in DATASETS.md and also made yaml files.

-------------------------------------------------------------------------------------------------

_BASE_: "../Base-RCNN-C4.yaml"
DE:
  CLASS_PROTOTYPES: "prototypes_init/aisoc_1shot.vitl14.bbox.p1.sk.pkl"
  BG_PROTOTYPES: "weights/initial/background/background_prototypes.vitl14.pth"
  BG_CLS_LOSS_WEIGHT: 0.2
  TOPK: 5
  SET_CD_VITO: True
  ATTN_FUSE_RATIO: 0.7
MODEL:
  META_ARCHITECTURE: "OpenSetDetectorWithExamples"
  BACKBONE:
    NAME: "build_dino_v2_vit"
    TYPE: "large" # base, small
  WEIGHTS: ""
  MASK_ON: False
  RPN:
    HEAD_NAME: StandardRPNHeadd`
    IN_FEATURES: ["res4"]
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  ROI_BOX_HEAD:
    NAME: ""
    NUM_FC: 0
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
DATASETS:
  TRAIN: ("aisoc_1shot",)
  TEST: ("aisoc_test",)
TEST:
  EVAL_PERIOD: 40
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (20, 35)
  MAX_ITER: 40
  WARMUP_ITERS: 10
  CHECKPOINT_PERIOD: 40
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: choice
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FORMAT: "RGB"

------------------------------------------------------------------------------------------

When I run bash main_results.sh, error below occurs.


[01/03 23:26:40 detectron2]: Full config saved to output/vitl/aisoc_1shot/config.yaml
('aisoc_test',)
Traceback (most recent call last):
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py", line 208, in <module>
    launch(
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py", line 196, in main
    trainer = Trainer(cfg)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py", line 381, in __init__
    model = self.build_model(cfg)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py", line 521, in build_model
    model = build_model(cfg)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/config/config.py", line 175, in wrapped
    init_func(self, **explicit_args)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/devit.py", line 525, in __init__
    dct = torch.load(class_prototypes_file)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'prototypes_init/aisoc_1shot.vitl14.bbox.p1.sk.pkl'

**Comment by Guanxiangcheng** [comment]
> > 有关详细说明，请参阅 [DATASETS.md](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/DATASETS.md)。如果您遇到任何问题，请随时再次与我联系。
> 
> 1. 将数据集转换为 COCO 格式
> 2. 将数据集拆分为训练集和测试集
> 3. 从训练集中选择 k-shot 样本
> 
> ![image](https://private-user-images.githubusercontent.com/142472364/399974393-c1275de9-83c6-4a44-8430-096653b6953e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjU0MjcsIm5iZiI6MTczNTk2NTEyNywicGF0aCI6Ii8xNDI0NzIzNjQvMzk5OTc0MzkzLWMxMjc1ZGU5LTgzYzYtNGE0NC04NDMwLTA5NjY1M2I2OTUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQwNDMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmI0ODI3Y2FmZTllZDliMzBmYzMyNTg2OWJiMDkxMDk4YWU5YzI1ODY4NzNmMzFjYjlhZDk1N2U1NTE1OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m1Ci6ZwPh88O4LhmS-pQZ8qs5pnHo8eNLgJUYg4KC8g)
> 
> 4. 添加自定义数据集
> 
> ![image](https://private-user-images.githubusercontent.com/142472364/399972733-f5b675cf-0397-45b8-a9fe-2af952af89ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjU0MjcsIm5iZiI6MTczNTk2NTEyNywicGF0aCI6Ii8xNDI0NzIzNjQvMzk5OTcyNzMzLWY1YjY3NWNmLTAzOTctNDViOC1hOWZlLTJhZjk1MmFmODllZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQwNDMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODFhMjliNWExZjY2OTNlNjI2OTdjNmVhMDgxYmRiOWI4MzliZDQ3YzdmYjM4OGY2YWMzZTZiYzg4MDRhYWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Edg8L3P9pswNU6dh9B2Z93yKCKp7TQFuFmuVNO3rtZ4)
> 
> 我在 builtin.py 中添加了我的自定义datasets_name
> 
> ![image](https://private-user-images.githubusercontent.com/142472364/399972507-39e64e80-e8d9-4b6e-a7ea-5e1b4ea045f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjU0MjcsIm5iZiI6MTczNTk2NTEyNywicGF0aCI6Ii8xNDI0NzIzNjQvMzk5OTcyNTA3LTM5ZTY0ZTgwLWU4ZDktNGI2ZS1hN2VhLTVlMWI0ZWEwNDVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQwNDMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDc3OTI1NmZiMjZmNzc4MmM3OTQ1N2RlNmNjMTQ2N2QyYWQ2ZGJlYTIwNzgxNTJkMDQ3MjU0YzljZDUzOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fOfarVoXbZbz9V116Aot7AnelHj12fKdSgNuFiT-GwM)
> 
> 还在 categories.py 中添加了 datasets_name 和 CLASS_NAME
> 
> 我已经在 DATASETS.md 中完成了所有过程，还制作了 yaml 文件。
> 
> _基地_：“../base-rcnn-c4.yaml“ DE： CLASS_PROTOTYPES： ”prototypes_init/aisoc_1shot.vitl14.bbox.p1.sk.pkl“ BG_PROTOTYPES： ”weights/initial/background/background_prototypes.vitl14.pth“ BG_CLS_LOSS_WEIGHT： 0.2 TOPK： 5 SET_CD_VITO： True ATTN_FUSE_RATIO： 0.7 型号： META_ARCHITECTURE： ”OpenSetDetectorWithExamples“ BACKBONE： 名称： ”build_dino_v2_vit” TYPE： “large” # base， small WEIGHTS： “” MASK_ON： False RPN： HEAD_NAME： StandardRPNHeadd' IN_FEATURES： [“res4”] ROI_HEADS： SCORE_THRESH_TEST： 0.001 ROI_BOX_HEAD： NAME： “” NUM_FC： 0 POOLER_RESOLUTION： 7 CLS_AGNOSTIC_BBOX_REG： True PIXEL_MEAN： [0.48145466， 0.4578275， 0.40821073]PIXEL_STD： [0.26862954， 0.26130258， 0.27577711] 数据集： 训练： （“aisoc_1shot”，） 测试： （“aisoc_test”，） 测试： EVAL_PERIOD： 40 求解器： IMS_PER_BATCH： 16 BASE_LR： 0.002 步骤： （20， 35） MAX_ITER： 40 WARMUP_ITERS： 10 CHECKPOINT_PERIOD： 40 输入： MIN_SIZE_TRAIN_SAMPLING： 选择MIN_SIZE_TRAIN：（640、672、704、736、768、800） MAX_SIZE_TRAIN：1333 MIN_SIZE_TEST：800 MAX_SIZE_TEST：1333 格式：“RGB”
> 
> 当我运行 bash main_results.sh 时，出现以下错误。
> 
> [01/03 23：26：40 detectron2]：完整配置保存到 output/vitl/aisoc_1shot/config.yaml （'aisoc_test'，） 回溯（最近一次调用最后）：文件 “/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py”，第 208 行，在 launch（ 文件 “/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/launch.py“，第 82 行，在启动 main_func（*args） 文件中 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py“，第 196 行，在主 trainer = Trainer（cfg） 文件中 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py“，第 381 行，**init** model = self.build_model（cfg） 文件 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py“，第 521 行，build_model model = build_model（cfg） 文件 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/build.py“，第 22 行，build_model model = META_ARCH_REGISTRY.get（meta_arch）（cfg） 文件 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/config/config.py“，第 175 行，换行的 init_func（self， **explicit_args） 文件 ”/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/devit.py“，第 525 行，**init** dct = torch.load（class_prototypes_file） 文件”/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py“，第 771 行，加载_open_file_like（f， 'rb'） 作为opened_file：文件”/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py“，第 270 行，_open_file_like返回_open_file（name_or_buffer， mode） 文件 “/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py”，第 251 行，**init** super（_open_file， self）。**init**（open（name， mode）） FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'prototypes_init/aisoc_1shot.vitl14.bbox.p1.sk.pkl'
> 
> 问题是，我应该如何制作 'aisoc_1shot.vitl14.bbox.p1.sk.pkl' 这个文件呢？

我也是遇到这种情况，已经搞了一个星期了，还灭有解决

**Comment by huangwei2913** [comment]
其实这个文档讲的不详细，应该先调用[build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh)生成原文件, 这些原文件就包含了这个权重文件的，你再试一下

**Comment by atti0127** [comment]
> 其实这个文档讲的不详细，应该先调用[build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh)生成原文件, 这些原文件就包含了这个权重文件的，你再试一下

-------------------------------------------------------------------------------------------------------------------------------

(cdfsod) bruno@bruno-System-Product-Name:~/Desktop/CDFSOD-benchmark$ bash build_prototypes.sh
prototypes_init folder already exists.
PYTHONPATH: None
Traceback (most recent call last):
  File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/extract_instance_prototypes.py", line 24, in <module>
    from fast_pytorch_kmeans import KMeans
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/__init__.py", line 1, in <module>
    from fast_pytorch_kmeans.kmeans import KMeans
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/kmeans.py", line 7, in <module>
    from .util import find_optimal_splits
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/util.py", line 4, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
extract_instance_prototypes with vitl for 1shot aisoc done, save at prototypes_init dir.
{'batch_size': 512,
 'device': 0,
 'epochs': 30,
 'inp': 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl',
 'momentum': 0.002,
 'normalize': 'yes',
 'num_prototypes': 1,
 'oneshot': False,
 'oneshot_sample_pool': 30,
 'queue_size': 8192,
 'save': 'yes',
 'save_tokens': 'no',
 'token_type': 'pat'}
load and preprocess dataset
Traceback (most recent call last):
  File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 181, in <module>
    fire.Fire(main)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 51, in main
    dataset = torch.load(inp)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl'
run_sinkhorn_cluster with vitl for 1shot aisoc done, save at prototypes_init dir.


----------------------------------------------------------------------------------------------------------------------------------

When I run build_prototypes.sh, error above occurs.

**Comment by huangwei2913** [comment]
还有就是数据集里面有点问题，也会影响生成不了这些权重的

**Comment by huangwei2913** [comment]
可以加微信讨论的哈（13247123363），这个数据集要求影像对应的注解里面都只有一个标签

**Comment by AImind** [comment]
> > 其实这个文档讲的不详细，应该先调用[build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh)生成原文件, 这些原文件就包含了这个权重文件的，你再试一下
> 
> (cdfsod) bruno@bruno-System-Product-Name:~/Desktop/CDFSOD-benchmark$ bash build_prototypes.sh prototypes_init folder already exists. PYTHONPATH: None Traceback (most recent call last): File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/extract_instance_prototypes.py", line 24, in from fast_pytorch_kmeans import KMeans File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/**init**.py", line 1, in from fast_pytorch_kmeans.kmeans import KMeans File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/kmeans.py", line 7, in from .util import find_optimal_splits File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/util.py", line 4, in import psutil ModuleNotFoundError: No module named 'psutil' extract_instance_prototypes with vitl for 1shot aisoc done, save at prototypes_init dir. {'batch_size': 512, 'device': 0, 'epochs': 30, 'inp': 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl', 'momentum': 0.002, 'normalize': 'yes', 'num_prototypes': 1, 'oneshot': False, 'oneshot_sample_pool': 30, 'queue_size': 8192, 'save': 'yes', 'save_tokens': 'no', 'token_type': 'pat'} load and preprocess dataset Traceback (most recent call last): File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 181, in fire.Fire(main) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 135, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 468, in _Fire component, remaining_args = _CallAndUpdateTrace( File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 51, in main dataset = torch.load(inp) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 771, in load with _open_file_like(f, 'rb') as opened_file: File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like return _open_file(name_or_buffer, mode) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 251, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl' run_sinkhorn_cluster with vitl for 1shot aisoc done, save at prototypes_init dir.
> 
> When I run build_prototypes.sh, error above occurs.

It seems that some dependencies are missing. Additionally, you can generate prototypes step by step instead of directly using build_prototypes.sh.

**Comment by atti0127** [comment]
> > > 其实这个文档讲的不详细，应该先调用[build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh)生成原文件, 这些原文件就包含了这个权重文件的，你再试一下
> > 
> > 
> > (cdfsod) bruno@bruno-System-Product-Name:~/Desktop/CDFSOD-benchmark$ bash build_prototypes.sh prototypes_init folder already exists. PYTHONPATH: None Traceback (most recent call last): File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/extract_instance_prototypes.py", line 24, in from fast_pytorch_kmeans import KMeans File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/**init**.py", line 1, in from fast_pytorch_kmeans.kmeans import KMeans File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/kmeans.py", line 7, in from .util import find_optimal_splits File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fast_pytorch_kmeans/util.py", line 4, in import psutil ModuleNotFoundError: No module named 'psutil' extract_instance_prototypes with vitl for 1shot aisoc done, save at prototypes_init dir. {'batch_size': 512, 'device': 0, 'epochs': 30, 'inp': 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl', 'momentum': 0.002, 'normalize': 'yes', 'num_prototypes': 1, 'oneshot': False, 'oneshot_sample_pool': 30, 'queue_size': 8192, 'save': 'yes', 'save_tokens': 'no', 'token_type': 'pat'} load and preprocess dataset Traceback (most recent call last): File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 181, in fire.Fire(main) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 135, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 468, in _Fire component, remaining_args = _CallAndUpdateTrace( File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "/home/bruno/Desktop/CDFSOD-benchmark/./tools/run_sinkhorn_cluster.py", line 51, in main dataset = torch.load(inp) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 771, in load with _open_file_like(f, 'rb') as opened_file: File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like return _open_file(name_or_buffer, mode) File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/serialization.py", line 251, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'prototypes_init/aisoc_1shot.vitl14.bbox.pkl' run_sinkhorn_cluster with vitl for 1shot aisoc done, save at prototypes_init dir.
> > When I run build_prototypes.sh, error above occurs.
> 
> It seems that some dependencies are missing. Additionally, you can generate prototypes step by step instead of directly using build_prototypes.sh.


------------------------------------

How can I generate prototype step by step? Is there anything  I can refer to? I would appreciate it if you could let me know.

**Comment by AImind** [comment]
```
python3 ./tools/extract_instance_prototypes.py   --dataset ${dataset}_${shot}shot --out_dir prototypes_init --model vit${model}14 --epochs 1 --use_bbox yes --without_mask True
      echo "extract_instance_prototypes with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."

python3 ./tools/run_sinkhorn_cluster.py  --inp  prototypes_init/${dataset}_${shot}shot.vit${model}14.bbox.pkl  --epochs 30 --momentum 0.002    --num_prototypes ${shot}
      echo "run_sinkhorn_cluster with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."
```

For more details ,please refer to [build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh).

**Comment by atti0127** [comment]
> ```
> python3 ./tools/extract_instance_prototypes.py   --dataset ${dataset}_${shot}shot --out_dir prototypes_init --model vit${model}14 --epochs 1 --use_bbox yes --without_mask True
>       echo "extract_instance_prototypes with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."
> 
> python3 ./tools/run_sinkhorn_cluster.py  --inp  prototypes_init/${dataset}_${shot}shot.vit${model}14.bbox.pkl  --epochs 30 --momentum 0.002    --num_prototypes ${shot}
>       echo "run_sinkhorn_cluster with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."
> ```
> 
> For more details ,please refer to [build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh).

-------------------------------------------------------------

1. python3 ./tools/extract_instance_prototypes.py     --dataset aisoc_5shot     --out_dir prototypes_init     --model vitl14     --epochs 1     --use_bbox yes     --without_mask True

2. python3 ./tools/run_sinkhorn_cluster.py     --inp prototypes_init/aisoc_5shot.vitl14.bbox.pkl     --epochs 30     --momentum 0.002     --num_prototypes 1

3. bash build_prototypes.sh

4. bash main_results.sh


Thank you so much for letting me know !! But there is one problem. When I run main, I get the following error. 

---------------------------------------------------------------------------------------------------------------------------

ERROR [01/10 00:46:03 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py", line 510, in run_step
    self._trainer.run_step()
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/devit.py", line 1252, in forward
    topk_class_indices = torch.topk(init_scores, class_topk, dim=1).indices
RuntimeError: selected index k out of range
[01/10 00:46:03 d2.engine.hooks]: Total training time: 0:00:03 (0:00:00 on hooks)
[01/10 00:46:03 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 4884M
Traceback (most recent call last):
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py", line 208, in <module>
    launch(
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/train_net.py", line 202, in main
    return trainer.train()
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py", line 500, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/defaults.py", line 510, in run_step
    self._trainer.run_step()
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/bruno/anaconda3/envs/cdfsod/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bruno/Desktop/CDFSOD-benchmark/tools/../detectron2/modeling/meta_arch/devit.py", line 1252, in forward
    topk_class_indices = torch.topk(init_scores, class_topk, dim=1).indices
RuntimeError: selected index k out of range

-----------------------------------------------------------

In my custom dataset, there is only 1 class. When it is 1shot, it works when I set topk=1 in the yaml file, but it doesn't work when it is 5shot. I think there is some point that I'm missing. Can you please tell me?

**Comment by atti0127** [comment]
> ```
> python3 ./tools/extract_instance_prototypes.py   --dataset ${dataset}_${shot}shot --out_dir prototypes_init --model vit${model}14 --epochs 1 --use_bbox yes --without_mask True
>       echo "extract_instance_prototypes with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."
> 
> python3 ./tools/run_sinkhorn_cluster.py  --inp  prototypes_init/${dataset}_${shot}shot.vit${model}14.bbox.pkl  --epochs 30 --momentum 0.002    --num_prototypes ${shot}
>       echo "run_sinkhorn_cluster with vit${model} for ${shot}shot ${dataset} done, save at prototypes_init dir."
> ```
> 
> For more details ,please refer to [build_prototypes.sh](https://github.com/lovelyqian/CDFSOD-benchmark/blob/main/build_prototypes.sh).



-------------------------------------

1. python3 ./tools/extract_instance_prototypes.py     --dataset xxxx_10shot     --out_dir prototypes_init     --model vitl14     --epochs 1     --use_bbox yes     --without_mask True

2. python3 ./tools/run_sinkhorn_cluster.py     --inp prototypes_init/xxxx_10shot.vitl14.bbox.pkl     --epochs 30     --momentum 0.002     --num_prototypes 10

3. bash build_prototypes.sh

----------------------------------------

Sorry for the late reply. Thank you so much for your kind information!
